apiVersion: v1
kind: ConfigMap
metadata:
  name: packetpulse-config
  namespace: packetpulse
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC_RAW: "raw_packets"
  KAFKA_TOPIC_PROCESSED: "processed_packets"
  KAFKA_TOPIC_ALERTS: "alerts"
  REDIS_URL: "redis://redis-service:6379/0"
  POSTGRES_URL: "postgresql+asyncpg://pp:pp_secret@postgres-service:5432/packetpulse"
  INTERFACE: "eth0"
  MODEL_PATH: "./models"
  PACKET_SERVICE_HEALTH_PORT: "8001"
  PROCESSING_SERVICE_HEALTH_PORT: "8002"
  DETECTION_SERVICE_HEALTH_PORT: "8003"
  API_GATEWAY_HEALTH_PORT: "8001"
