apiVersion: v1
kind: Service
metadata:
  name: processing-service
  namespace: packetpulse
spec:
  selector:
    app: processing-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
