"""
Data loader — reads from the C++ engine's output.json file.

Falls back to the built-in mock data when the file is absent or
contains incomplete sections, so the API always has something to serve.
"""

import json
import os
import logging
from pathlib import Path

logger = logging.getLogger("packetpulse")

# Path to the JSON file generated by the C++ DPI engine.
# Resolve relative to the project root (one level up from /api).
_DEFAULT_JSON_PATH = Path(__file__).resolve().parent.parent / "output.json"
JSON_PATH = Path(os.getenv("DPI_OUTPUT_JSON", str(_DEFAULT_JSON_PATH)))


def _read_json() -> dict | None:
    """Return the parsed JSON dict, or None if the file is missing / invalid."""
    try:
        if JSON_PATH.is_file():
            with open(JSON_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)
            logger.info("Loaded DPI data from %s", JSON_PATH)
            return data
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Failed to read %s: %s", JSON_PATH, exc)
    return None


def load_stats() -> dict | None:
    """Load the 'stats' section from output.json."""
    data = _read_json()
    if data and "stats" in data:
        return data["stats"]
    return None


def load_flows() -> list | None:
    """Load the 'flows' section from output.json."""
    data = _read_json()
    if data and "flows" in data:
        return data["flows"]
    return None


def load_domains() -> list | None:
    """Load the 'domains' section from output.json."""
    data = _read_json()
    if data and "domains" in data:
        return data["domains"]
    return None
